POST http://localhost:8080/api/user/create_account HTTP/1.1
Content-Type: application/json

{
    "userName": "john.traudt10",
    "passwordHash": "super10",
    "email": "jt10@streets.edu",
    "firstName": "John",
    "lastName": "B Traudt",
    "userRoleId": "1"
}

###

POST http://localhost:8080/api/user/authenticate HTTP/1.1
Content-Type: application/json

{
    "userName": "john.traudt10",
    "passwordHash": "super10"
}