POST http://localhost:8080/api/user HTTP/1.1
Content-Type: application/json

{
    "userName": "john.traudt19103",
    "passwordHash": "12345678901234567890",
    "email": "jt1990@streets.edu",
    "firstName": "John",
    "lastName": "B Traudt",
    "userRoleId": "1"
}

###

POST http://localhost:8080/api/user/authenticate HTTP/1.1
Content-Type: application/json

{
    "userName": "john.traudt19103",
    "passwordHash": "12345678901234567890"
}