@url = http://localhost:8080/api/review

GET {{url}} HTTP/1.1

###
GET {{url}}/8 HTTP/1.1

###
POST {{url}} HTTP/1.1
Content-Type: application/json 

{
  "rating": 4,
  "comment": "Super delicious.", 
  "date": "2020-11-02", 
  "userId": 2, 
  "recipeId": 3
}

###
PUT {{url}}/8 HTTP/1.1
Content-Type: application/json 

{
  "reviewId": 8,
  "rating": 1,
  "comment": "Super delicious. Not.", 
  "date": "2020-11-02", 
  "userId": 2, 
  "recipeId": 2
}

###
DELETE {{url}}/2 HTTP/1.1
